kafkaclient.web/Models/ErrorViewModel.cs
namespace kafkaclient.web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

kafkaclient.web/Components/BarTreeViewComponent.cs
using kafkaclient.web.Core.Dto;
using kafkaclient.web.Core.Services;
using Microsoft.AspNetCore.Mvc;

namespace kafkaclient.web.Components;

public class BarTreeViewComponent : ViewComponent
{
    private readonly ClusterService _clusterService;
    
    public BarTreeViewComponent(ClusterService clusterService)
    {
        _clusterService = clusterService;
    }

    public async Task<IViewComponentResult> InvokeAsync()
    {
        var query_paging = new PagingRequest { Offset = 1, Limit = 100 };
        var query_filter = new ClusterFilterRequest { Status = true };
        var query_order_by = new ClusterOrderByRequest {};
        var data = await _clusterService.GetAllAsync(query_paging, query_filter, query_order_by);
        
        return View(data);
    }
}

kafkaclient.web/Controllers/ClusterApiController.cs
using kafkaclient.web.Core.Dto;
using kafkaclient.web.Core.Services;
using Microsoft.AspNetCore.Mvc;

namespace kafkaclient.web.Controllers;

[Route("api/[controller]")]
[ApiController]
public class ClusterApiController : ControllerBase
{
    private readonly ClusterService _clusterService;

    public ClusterApiController(ClusterService clusterService)
    {
        _clusterService = clusterService;
    }

    [HttpGet]
    [ProducesResponseType(typeof(PageResponse<ClusterDto>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> GetAllAsync(
        [FromQuery]PagingRequest query_paging,
        [FromQuery]ClusterFilterRequest query_filter,
        [FromQuery]ClusterOrderByRequest? query_order_by)
    {
        var data = await _clusterService.GetAllAsync(query_paging, query_filter, query_order_by);
        return Ok(data);
    } 

    [HttpGet("{id}")]
    [ProducesResponseType(typeof(ClusterDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    public async Task<IActionResult> GetByIdAsync(
        [FromRoute]ClusterRouteRequest paramRoute)
    {
        var data = await _clusterService.GetByIdAsync(paramRoute.Id);
        return Ok(data);
    } 

    [HttpPost()]
    [ProducesResponseType(typeof(CreateResponse<ClusterDto>), StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Post([FromBody]ClusterRequest request)
    {
        var response = await _clusterService.CreateAsync(request);
        return Created($"/cluster/{response.Id}", new CreateResponse<ClusterDto>(){
            Status = "OK",
            Message = "Cluster creado exitosamente.",
            Data = response
        });
    }

    [HttpPut("{id}")]
    [ProducesResponseType(typeof(UpdateResponse<ClusterDto>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Update(
        [FromRoute]ClusterRouteRequest paramsRoute, 
        [FromBody]ClusterRequest request)
    {
        var response = await _clusterService.UpdateAsync(paramsRoute.Id, request);
        return Ok(new UpdateResponse<ClusterDto>{
            Status = "OK",
            Message = "Cluster actualizado exitosamente.",
            Data = response
        });
    }

    [HttpPut("status/{id}")]
    [ProducesResponseType(typeof(UpdateResponse<ClusterDto>), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<IActionResult> UpdateStatus(
        [FromRoute]ClusterRouteRequest paramsRoute)
    {
        var response = await _clusterService.UpdateAsync(paramsRoute.Id);
        return Ok(new UpdateResponse<ClusterDto>(){
            Status = "OK",
            Message = "Cluster actualizado exitosamente.",
            Data = response
        });
    }

    [HttpDelete("{id}")]
    [ProducesResponseType(typeof(DeleteResponse), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status404NotFound)]
    public async Task<IActionResult> Delete([FromRoute]ClusterRouteRequest paramsRoute)
    {
        var response = await _clusterService.DeleteAsync(paramsRoute.Id);
        return Ok(response);
    }
}

kafkaclient.web/Controllers/ClusterClientApiController.cs
using kafkaclient.web.Core.Dto;
using kafkaclient.web.Core.Services;
using Microsoft.AspNetCore.Mvc;

namespace kafkaclient.web.Controllers;

[Route("api/[controller]")]
[ApiController]
public class ClusterClientApiController : ControllerBase
{
    private readonly ClusterClientService _clusterClientService;
    public ClusterClientApiController(ClusterClientService clusterClientService)
    {
        _clusterClientService = clusterClientService;
    }


    [HttpPost("{id}/connect")]
    [ProducesResponseType(typeof(ClusterKafkaDto), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ErrorResponse), StatusCodes.Status400BadRequest)]
    public async Task<ActionResult> ConnectCluster(int id)
    {
        var clusterKafkaInfo = await _clusterClientService.ConnectClusterAsync(id);
        return Ok(clusterKafkaInfo);
    }

    [HttpGet("{id}/topics/{topic}/partitions")]
    public async Task<ActionResult<IEnumerable<PartitionDto>>> GetTopicPartitions(int id, string topic)
    {
        var partitions = await _clusterClientService.GetTopicPartitionsAsync(id, topic);
        return Ok(partitions);
    }

    [HttpGet("{id}/topics/{topic}/partitions/{partition}/messages")]
    public async Task<ActionResult<IEnumerable<MessageDto>>> GetPartitionMessages(
        int id, string topic, int partition, [FromQuery] long offset, [FromQuery] int limit = 10)
    {
        var messages = await _clusterClientService.GetPartitionMessagesAsync(id, topic, partition, offset, limit);
        if (messages == null)
        {
            return NotFound();
        }
        return Ok(messages);
    }

    [HttpPost("{id}/topics")]
    public async Task<IActionResult> CreateTopic(int id, [FromBody]TopicRequest request)
    {
        await _clusterClientService.CreateTopicAsync(id, request);
        return Ok();
    }

    [HttpPost("{id}/consumergroups")]
    public async Task<IActionResult> CreateConsumerGroup(int id, [FromBody]ConsumerGroupRequest request)
    {
        await _clusterClientService.CreateConsumerGroupAsync(id, request);
        return Ok();
    }

    [HttpPost("{id}/messages")]
    public async Task<IActionResult> PublishMessage(int id, [FromBody]PublishMessageRequest request)
    {
        await _clusterClientService.PublishMessageAsync(id, request);
        return Ok();
    }
}

kafkaclient.web/Controllers/ClusterController.cs
using kafkaclient.web.Models;
using Microsoft.AspNetCore.Mvc;

namespace kafkaclient.web.Controllers;

public class ClusterController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public ClusterController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    [HttpGet]
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
}

kafkaclient.web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using kafkaclient.web.Models;

namespace kafkaclient.web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

kafkaclient.web/Views/Cluster/Create.cshtml
@{
    ViewData["Title"] = "Create Cluster";
}

<div class="form-container">
    <h2>Agregar Cluster</h2>
    <form id="createClusterForm">
        <div class="form-group">
            <label for="clusterName">Cluster Name:</label>
            <input type="text" id="Name" name="clusterName">
            <span class="text-danger" id="NameError"></span>
        </div>
        <div class="form-group">
            <label for="kafkaVersion">Kafka Cluster Version:</label>
            <input type="text" id="Version" name="kafkaVersion">
            <span class="text-danger" id="VersionError"></span>
        </div>
        <div class="form-group">
            <label for="zookeeperHost">Zookeeper Host:</label>
            <input type="text" id="Host" name="zookeeperHost">
            <span class="text-danger" id="HostError"></span>
        </div>
        <div class="form-group">
            <label for="chrootPath">Chroot Path:</label>
            <input type="text" id="Path" name="chrootPath">
            <span class="text-danger" id="PathError"></span>
        </div>
        <div class="buttons">
            <button type="button" id="saveButton" class="win98-button">Agregar</button>
            <button type="button" id="testConnection" class="win98-button">Test Connection</button>
        </div>
    </form>
    <div id="loader" style="display:none;">Loading...</div>
</div>

@section Scripts
{
    <script src="~/js/createCluster.js"></script>
}

kafkaclient.web/Views/Cluster/Index.cshtml
@{
    ViewData["Title"] = "List Clusters";
}

kafkaclient.web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

kafkaclient.web/Views/Shared/BarTree.cshtml
<div class="file-tree-container">
    <div class="buttons">
        <button id="addButton" class="win98-button"><i class="fas fa-plus"></i> Agregar</button>
        <button id="deleteButton" class="win98-button"><i class="fas fa-minus"></i> Eliminar</button>
    </div>
    <div id="elementsTree">
        <ul>
            <li id="cluster-1">
                <span class="caret">
                    <span class="toggle-icon"><i class="fas fa-plus"></i></span> 
                    <i class="fas fa-folder"></i> Clusters
                </span>
                <ul class="nested">
                    <li id="localhost">
                        <span class="caret">
                            <span class="toggle-icon"><i class="fas fa-plus"></i></span> 
                            <i class="fas fa-server"></i> localhost
                        </span>
                        <ul class="nested">
                            <li id="brokers-localhost">
                                <span class="caret">
                                    <span class="toggle-icon"><i class="fas fa-plus"></i></span> 
                                    <i class="fas fa-database"></i> Brokers
                                </span>
                                <ul class="nested ">
                                    <li id="uno:9092">
                                        <span class="caretli">
                                            <i class="fas fa-network-wired"></i> uno:9092
                                        </span>
                                    </li>
                                </ul>
                            </li>
                            <li id="topics-localhost">
                                <span class="caret">
                                    <span class="toggle-icon"><i class="fas fa-plus"></i></span> 
                                    <i class="fas fa-stream"></i> Topics
                                </span>
                                <ul class="nested">
                                    <li id="uno">
                                        <span class="caretli">
                                            <i class="fas fa-dot-circle"></i> uno
                                        </span>
                                    </li>
                                    <li id="dos">
                                        <span class="caretli">
                                            <i class="fas fa-dot-circle"></i> dos
                                        </span>
                                    </li>
                                </ul>
                            </li>
                            <li id="consumers-localhost">
                                <span class="caret">
                                    <span class="toggle-icon"><i class="fas fa-plus"></i></span> 
                                    <i class="fas fa-users"></i> Consumers
                                </span>
                                <ul class="nested">
                                    <li id="test-consumer">
                                        <span class="caretli">
                                            <i class="fas fa-user"></i> test-consumer
                                        </span>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

kafkaclient.web/Views/Shared/Components/BarTree/Default.cshtml
@using kafkaclient.web.Core.Dto

@model PageResponse<ClusterDto>

<div class="file-tree-container">
    <div class="buttons">
        <button id="addButton" class="win98-button"><i class="fas fa-plus"></i> Agregar</button>
        <button id="deleteButton" class="win98-button"><i class="fas fa-minus"></i> Eliminar</button>
    </div>
    <div id="elementsTree">
        <ul>
            <li id="cluster-1">
                <span class="caret">
                    <span class="toggle-icon"><i class="fas fa-plus"></i></span> 
                    <i class="fas fa-folder"></i> Clusters
                </span>
                @foreach (var cluster in Model.Data)
                {
                    <ul class="nested">
                        <li id="clusters-@cluster.Slug">
                            <span class="caret">
                                <span class="toggle-icon"><i class="fas fa-plus"></i></span> 
                                <i class="fas fa-server"></i> @cluster.Name
                            </span>
                        </li>
                    </ul>
                }
                
            </li>
        </ul>
    </div>
</div>

kafkaclient.web/Views/Shared/DropdownMenu.cshtml
<div id="contextMenuCluster" class="context-menu" style="display:none;">
    <ul>
        <li>Agregar</li>
    </ul>
</div>


<div id="contextMenuClustersConn" class="context-menu" style="display:none;">
    <ul>
        <li>Conectar</li>
        <li>Desconectar</li>
    </ul>
</div>

kafkaclient.web/Views/Shared/_Layout.cshtml
@{
    var createClusterUrl = Url.Action("Create", "Cluster");
    var listClusterUrl = Url.Action("Index", "Cluster");
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Kafka Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/tree.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/scroll.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/input.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/button.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/loader.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dropdownmenu.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/kafkaclient.web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kafka Client</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @* <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div> *@
            </div>
        </nav>
    </header>
    
    <div class="main-container">
        @* @await Html.PartialAsync("BarTree") *@
        @(await Component.InvokeAsync("BarTree"))
        @await Html.PartialAsync("DropdownMenu")
        <div class="content-container">
            @RenderBody()
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>
        var createClusterUrl = '@createClusterUrl';
        var listClusterUrl = '@listClusterUrl';
    </script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/tree.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>